### ISSUE TITLE
Putting a sign in front of an elevator causes it to stop working

### ISSUE THREAD

**Issue by webdo** [Moyettes/IronElevators#1]
Hi,
First of all, amazing plugin, thank you for sharing it!

I just got a small issue to point out:
If you put a sign in front of an elevator, the others cannot reach it anymore.

![2022-12-12_17 31 41](https://user-images.githubusercontent.com/470782/207169350-7ebfd848-95f1-4bb4-bc2a-19a653f4a24e.png)

It's probably due to the fact that the sign position is exactly one block above the elevator and it collides?

Thank you!

**Comment by Moyettes** [comment]
Thank you, uploaded fix. Version 1.6.2

**Comment by webdo** [comment]
Thank you, that was crazy fast!
